FROM python:3.11.8

WORKDIR /user/src/app

ENV PYTHONDONTWRITEBYTECODE=1
ENV PYTHONUNBUFFERED=1

COPY ./requirements.txt /user/src/app/requirements.txt

RUN pip install -r requirements.txt

COPY . /user/src/app/

